[package]
name = "try_buf"
version = "0.1.2"
edition = "2021"
description = "This crate provides no-panic API for bytes::Buf"
readme = "README.md"
repository = "https://github.com/wheird-lee/try_buf"
license = "MIT"

[dependencies]
paste = "1.0"
bytes = "1.2"
